### ISSUE TITLE
Signup | POST

### ISSUE THREAD

**Issue by Anies12** [FACG6/Gaza-Freelancing-Community#21]
### Signup Route | POST 

 - ```/signup```, route for signing up. 
--------
### Acceptance Criteria :
- [x] Validation of the request. 
- [x] Query checkEmail.
- [x] Query insertUsers.
- [x] Testing
  
 -----  

### Request Validation  : 
 the body of the request must contain ```firstname``` property with at least 3 characters,<br> ```lastname``` property with at least 3 characters, <br> ```mobile_number``` property with at least 10 characters , <br> ``` email ``` property with email format, <br> ```freelancer_url``` property, <br> ```specialization_id``` property, <br> ```Photo_url``` property, <br> ``` password``` property with at least 5 characters.
  - [x] request body must be in JSON format.
  - [x] check the request body.
  - [x] the email must be new, not already stored in the database.

#### The shape of the ideal request body  : 
```javascript
 const userInfo = {
    firstSection: {
      firstname: 'Angham',
      lastname: 'Aabed',
      mobile_number: '0000000',
      email: 'a@gmail.com',
    },
    secondSection: {
      specalization_id: 1,
      freelancer_url: 'https://github.com/angham.com',
      photo_url: 'https://www.iconspng.com/image/36709/face-avatar-man-male-handsome-3.jpg',
    },
    thirdSection: {
      password: 'Aa123fgfg',
    },
  };
```

### The query   : 
the query function must take the ``` email ``` and returns a row.
if the email is already used,  then the same email is returned.
if it doesn't exist in the database, an empty row is returned.
then we hash the password coming from the request and store it in the database using another query.

example : 
```javascript
const user = { firstname:'User', 
   lastname: 'last name',
   mobile_number: 0599000000,
   email: 'asdf@asdf.com',
   specialization_id: 1,
   freelancer_url: 'www.abc.com/user-46546',
   photo_url : 'www.photo.com/dfg/546',
   password : '$agagag&jhk123'}
   checkEmail(user.email); 
  returns: 
   // [{ id: 1, 
   // fname: 'User'
   // lname: 'last name' ,
   // mobile_no : '0599000000',
   // freelancer_url : 'www.abc.com/user-46546',
   // photo_url : 'www.abc.com/ajshghsgshb',
   // birthday : 'dd/mm/yyyy'
   // specalization_id : 1 ,
   //password: $agagag&jhk123' }];
```
### Testing : 
the test function should test the operation of the route iteself and thus the queries used : 
- [x] testing for route ``` /signup ``` | POST
- [x] testing for checkEmail query function
-----
####  Sucessfull Path :

 POST /signup request body : 
``` { firstname:'User',
 lastname: 'last name',
 mobile_number: 0599000000,
 email: 'asdf@asdf.com',
 specialization_id: 'front-end developer',
 freelancer-url: 'www.abc.com/user-46546',
 photo_url: 'www.photo.com/dfg/546',
 password : '$agagag&jhk123' '}

{ status: 'OK' , status_code: 200, status_msg: ' successfull Operation'}
```
####  Error Path : 

POST /signup request body : 

|client | server |
|--|--|
| ``` {  email: "asdfasdfcom" password : null } ``` | --->|
|---> | ``` { status: 'ERROR', status_msg: 'bad request', status_code: 400 } ```|

**Comment by kannanhassouna** [comment]
:+1:  but where the example

**Comment by Anies12** [comment]
still working on it :)
